- name: Take screenshot
  run: |
    chromium-browser \
      --headless \
      --no-sandbox \
      --disable-dev-shm-usage \
      --disable-gpu \
      --hide-scrollbars \
      --window-size=2100,10000 \
      --screenshot=leaderboard.png \
      https://hdlan-info.github.io/boom-beach-team-8C0299VL/
